schema = 1
platform = "linux32"
component = "steamclient"
module_name = "steamclient.so"
module_sha256 = "50ac6ce62efaa992ceb4c4115798a06d13c82c46429319648dbfc203038581c0"
module_size = 49757220
gnu_build_id = "da30f7b2532cd4ac1c6a5b196c94805b59156109"
steam_version = 1786491548
consumer_commit = "1668847593433088472814782be29c55734345e5"
minimum_consumer_schema = 1
revision = 1
source = "deterministic"

[[locators]]
symbol = "Patterns::CAPIJob::GetPlayerStats"
name = "CAPIJob::GetPlayerStats"
target_rva = 26952064
match_rva = 26960687
signature = "E8 ? ? ? ? 83 C4 10 89 C5 E9 ? ? ? ? ? ? 80 BE ? ? ? ? 00"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CDepotDownloadMgr::BYldRequestDepotManifest"
name = "CDepotDownloadMgr::BYldRequestDepotManifest"
target_rva = 20354992
match_rva = 20354992
signature = "55 B9 FD FF FF FF 89 E5 57 E8 ? ? ? ? 81 C7 ? ? ? ? 56 53 83 EC 7C 8B 45 14 8B 55 18"
follow_mode = "None"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CDepotDownloadMgr::BuildDepotDependency"
name = "CDepotDownloadMgr::BuildDepotDependency"
target_rva = 18499584
match_rva = 18499584
signature = "E8 ? ? ? ? 05 ? ? ? ? 55 89 E5 57 56 53 81 EC 8C 04 00 00 8B 55 10 8B 7D 0C 89 85 A0 FB FF FF 8B 45 08"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CDepotDownloadMgr::EvaluateConfigChanges"
name = "CDepotDownloadMgr::EvaluateConfigChanges"
target_rva = 17046666
match_rva = 17046666
signature = "55 89 E5 57 56 53 81 EC DC 00 00 00 89 85 50 FF FF FF 8B 45 10 89 85 40 FF FF FF 8B 45 08 8B 40 04"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CDepotDownloadMgr::OnChunkUnpackedReg"
name = "CDepotDownloadMgr::OnChunkUnpacked[regparm3]"
target_rva = 20518912
match_rva = 20518912
signature = "55 89 E5 57 E8 ? ? ? ? 81 C7 ? ? ? ? 56 89 C6 53 81 EC 7C 04 00 00 8B 45 0C 89 95 90 FB FF FF 89 8D 8C FB FF FF 89 85 94 FB FF FF"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CDepotDownloadMgr::OnChunkUnpackedStack"
name = "CDepotDownloadMgr::OnChunkUnpacked[cdecl]"
target_rva = 20500128
match_rva = 20500128
signature = "55 89 E5 57 56 E8 ? ? ? ? 81 C6 ? ? ? ? 53 81 EC 7C 04 00 00 8B 45 0C 8B 7D 08 89 85 90 FB FF FF 8B 45 10 89 85 8C FB FF FF"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CDepotDownloadMgr::PrepareDepotDownload"
name = "CDepotDownloadMgr::PrepareDepotDownload"
target_rva = 16746848
match_rva = 16746848
signature = "55 89 E5 57 56 E8 ? ? ? ? 81 C6 ? ? ? ? 53 83 EC 60 8B 7D 08 8B 45 18 8B 55 1C FF 75 20 89 45 98 52 50 FF 75 14 89 55 9C FF 75 10 FF 75 0C 57 E8 ? ? ? ? 8B 47 4C 83 C4 20 83 F8 FF"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CDepotDownloadMgr::ProcessDepotManifest"
name = "CDepotDownloadMgr::ProcessDepotManifest"
target_rva = 16745552
match_rva = 16745552
signature = "E8 ? ? ? ? 05 ? ? ? ? 55 89 E5 57 56 53 83 EC 4C 8B 55 1C 89 45 C0 8B 45 18 89 55 CC 89 45 C8"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CJobMgr::BRouteMsgToJob"
name = "CJobMgr::BRouteMsgToJob"
target_rva = 45135104
match_rva = 45135104
signature = "55 89 E5 57 56 E8 ? ? ? ? 81 C6 ? ? ? ? 53 83 EC 7C 8B 45 08 8B 4D 14 89 45 90 8B 45 0C 89 4D A0 89 45 88 8B 45 10 89 45 A4 65 8B 0D 14 00 00"
follow_mode = "None"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CPackageInfoCache::LoadPackage"
name = "CPackageInfoCache::LoadPackage"
target_rva = 16656304
match_rva = 16654098
signature = "E8 ? ? ? ? 83 C4 10 84 C0 0F 84 ? ? ? ? 8B 95 ? ? FF FF 8B 7A 18 83 FF FF"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CProtoBufMsgBase::InitFromPacket"
name = "CProtoBufMsgBase::InitFromPacket"
target_rva = 45551824
match_rva = 17362553
signature = "E8 ? ? ? ? 58 8B 45 ? 8B 8D"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CProtoBufMsgBase::Send"
name = "CProtoBufMsgBase::Send"
target_rva = 45553632
match_rva = 17807226
signature = "E8 ? ? ? ? 59 5A 50 56 E8 ? ? ? ? 83 C4 0C"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CRemoteClientManager::RecvPkt"
name = "CRemoteClientManager::RecvPkt"
target_rva = 24364944
match_rva = 24364944
signature = "55 89 E5 57 56 E8 ? ? ? ? 81 C6 ? ? ? ? 53 83 EC 1C 8B 86 ? 08 00 00 8B 00 85 C0 0F 85 ? ? ? ? C7 45 E4 00 00 00 00 83 EC 08 89 F3 6A 01 FF 75 0C E8 ? ? ? ? 89 C7 83 C4 10 85 C0 0F 84 ? ? ? ? 83 EC 0C 50"
follow_mode = "None"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CSteamEngine::Init"
name = "CSteamEngine::Init"
target_rva = 25056096
match_rva = 25203838
signature = "E8 ? ? ? ? 83 C4 10 8D 83 ? ? ? ? 83 EC 0C 89 AB"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CSteamEngine::Offset_User"
name = "CSteamEngine::m_pUser"
target_rva = 25179633
match_rva = 25179633
signature = "8B 80 ? ? ? ? FF 75 ? 8D 34"
follow_mode = "None"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CSteamEngine::SetAppIdForCurrentPipe"
name = "CSteamEngine::SetAppIdForCurrentPipe"
target_rva = 25114592
match_rva = 20560681
signature = "E8 ? ? ? ? E9 ? ? ? ? ? ? ? ? ? 8B 85 ? ? ? ? 83 EC 08 FF B5"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CSteamMatchmakingServers::GetServerDetails"
name = "CSteamMatchmakingServers::GetServerDetails"
target_rva = 23755120
match_rva = 23755222
signature = "89 45 ? 83 C4 10 83 EC 0C 89 F3"
follow_mode = "PrologueUpwards"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CSteamMatchmakingServers::RequestInternetServerList"
name = "CSteamMatchmakingServers::RequestInternetServerList"
target_rva = 23751936
match_rva = 23751973
signature = "C7 04 24 ? ? 00 00 E8 ? ? ? ? 5A 89 45 ? 59 FF B6 ? ? ? ? FF B6 ? ? ? ? FF B6 ? ? ? ? FF B6 ? ? ? ? FF B6 ? ? ? ? 6A 01"
follow_mode = "PrologueUpwards"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CUser::CheckAppOwnership"
name = "CUser::CheckAppOwnership"
target_rva = 25713088
match_rva = 16781011
signature = "E8 ? ? ? ? 88 45 ? 83 C4 10 84 C0 0F 84 ? ? ? ? 8B 45 ? 80 7D ? 00"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CUser::GetSubscribedApps"
name = "CUser::GetSubscribedApps"
target_rva = 25765856
match_rva = 27029698
signature = "E8 ? ? ? ? 89 C6 83 C4 10 85 C0 0F 84 ? ? ? ? 8B 9D ? ? ? ? 39 D8"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CUser::NotifyLicensesUpdated"
name = "CUser::NotifyLicensesUpdated"
target_rva = 25695664
match_rva = 25695664
signature = "55 89 E5 57 56 53 E8 ? ? ? ? 81 C3 ? ? ? ? 81 EC ? ? ? ? 8B 45 08 8B B8 ? ? 00 00 89 9D ? ? FF FF 85 FF"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CUser::PostCallback"
name = "CSteamEngine::PostCallback"
target_rva = 16940704
match_rva = 26377431
signature = "E8 ? ? ? ? 8D 86 ? ? ? ? 83 C4 18 68 F6 01 00 00"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CUser::UpdateAppOwnershipTicket"
name = "IClientUser::UpdateAppOwnershipTicket"
target_rva = 25770672
match_rva = 17340376
signature = "E8 ? ? ? ? E9 ? ? ? ? ? ? ? ? ? ? 8D 45 ? 89 45 ? EB"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CUtlMemory::Grow"
name = "CUtlMemory::Grow"
target_rva = 16701264
match_rva = 16657084
signature = "E8 ? ? ? ? 8B 85 ? ? FF FF 83 C4 10 8B 40 44 89 85 ? ? FF FF 83 C0 01 E9"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::CWebSocketConnection::BBuildAndAsyncSendFrame"
name = "CWebSocketConnection::BBuildAndAsyncSendFrame"
target_rva = 47944432
match_rva = 47944432
signature = "55 89 E5 57 E8 ? ? ? ? 81 C7 ? ? ? ? 56 53 81 EC AC 00 00 00 8B 45 10 8B 55 08 89 85 ? ? FF FF 89 95 ? ? FF FF 65 A1 14 00 00 00"
follow_mode = "None"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::FamilyGroupRunningApp"
name = "FamilyGroupRunningApp"
target_rva = 25920784
match_rva = 17399431
signature = "E8 ? ? ? ? 83 C4 10 83 EC 08 C7 46 ? 01 00 00 00 C6 46 ? 01 56 57 E8 ? ? ? ? 83 C4 1C B8 01 00 00 00 5B 5E 5F 5D C3 ? ? ? ? ? ? ? 83 EC 04"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientAppManager::BCanRemotePlayTogether"
name = "IClientAppManager::BCanRemotePlayTogether"
target_rva = 16783920
match_rva = 16783957
signature = "58 5A FF 74 24 ? 56 E8 ? ? ? ? 83 C4 10 85 C0 74"
follow_mode = "PrologueUpwards"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientAppManager::RunIPCFrame"
name = "IClientAppManager::RunIPCFrame"
target_rva = 21601408
match_rva = 21601484
signature = "E8 ? ? ? ? 8B 85 ? ? ? ? 83 C4 10 3D B7 85 0A 7A"
follow_mode = "PrologueUpwards"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientApps::RunIPCFrame"
name = "IClientApps::RunIPCFrame"
target_rva = 21581104
match_rva = 21581180
signature = "E8 ? ? ? ? 8B 85 ? ? ? ? 83 C4 10 3D 37 9C 88 A6"
follow_mode = "PrologueUpwards"
resolver = "ipcframe-root"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientRemoteStorage::RunIPCFrame"
name = "IClientRemoteStorage::RunIPCFrame"
target_rva = 21845664
match_rva = 21845740
signature = "E8 ? ? ? ? 8B 85 ? ? ? ? 83 C4 10 3D 6C E8 2F 87"
follow_mode = "PrologueUpwards"
resolver = "ipcframe-root"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientUGC::RunIPCFrame"
name = "IClientUGC::RunIPCFrame"
target_rva = 22217216
match_rva = 22217292
signature = "E8 ? ? ? ? 8B 85 ? ? ? ? 83 C4 10 3D 62 0C D2 71"
follow_mode = "PrologueUpwards"
resolver = "ipcframe-root"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientUser::BLoggedOn"
name = "IClientUser::BLoggedOn"
target_rva = 18141056
match_rva = 18139557
signature = "E9 ? ? ? ? ? ? ? ? ? ? 5B 5E 5F FF E0"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientUser::BUpdateAppOwnershipTicket"
name = "IClientUser::BUpdateAppOwnershipTicket"
target_rva = 25975440
match_rva = 25975594
signature = "83 EC 0C 89 F3 8B 7D ? FF 30 E8 ? ? ? ? 83 C4 10 83 FF 01 77 ? 84 C0 75 ? 80 7D ? 00 74 ? 80 7D ? 00 0F 84 ? ? ? ? 8D 65"
follow_mode = "PrologueUpwards"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientUser::GetAppOwnershipTicketExtendedData"
name = "IClientUser::GetAppOwnershipTicketExtendedData"
target_rva = 25969552
match_rva = 25969567
signature = "83 EC 24 FF 74 24 ? 8B 44 24"
follow_mode = "PrologueUpwards"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientUser::GetSteamId"
name = "IClientUser::GetSteamID"
target_rva = 21064912
signature = "E8 ? ? ? ? 89 D8 83 C4 0C 83 C4 08 5B C2 04 00 ? 83 EC 08 50 53 FF D2 89 D8 83 C4 0C 83 C4 08 5B C2 04 00"
follow_mode = "Relative"
resolver = "relative-convergence"
required = true
match_count = 20
target_count = 1

[[locators]]
symbol = "Patterns::IClientUser::IsUserSubscribedAppInTicket"
name = "IClientUser::IsUserSubscribedAppInTicket"
target_rva = 16953168
match_rva = 20577594
signature = "E8 ? ? ? ? 89 C3 83 C4 20 8B ? ? ? ? ? 8B"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientUser::RequiresLegacyCDKey"
name = "IClientUser::RequiresLegacyCDKey"
target_rva = 25966080
match_rva = 25966167
signature = "75 ? 83 C4 1C 31 C0 5B 5E 5F 5D C3 ? ? ? ? ? 8B 44 24 ? 83 C4 1C 89 F9 89 F2 5B 5E 5F 5D 2D ? ? 00 00"
follow_mode = "PrologueUpwards"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientUser::RunIPCFrame"
name = "IClientUser::RunIPCFrame"
target_rva = 21104016
match_rva = 21104092
signature = "E8 ? ? ? ? 8B 85 ? ? ? ? 83 C4 10 3D 10 A3 86 73"
follow_mode = "PrologueUpwards"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientUserStats::RunIPCFrame"
name = "IClientUserStats::RunIPCFrame"
target_rva = 21778736
match_rva = 21778812
signature = "E8 ? ? ? ? 8B 85 ? ? ? ? 83 C4 10 3D 8F 65 6D 87"
follow_mode = "PrologueUpwards"
resolver = "ipcframe-root"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientUtils::Offset_GetPipeIndex"
name = "IClientUtils::m_PipeIndex"
target_rva = 25274218
match_rva = 25274218
signature = "8B 91 ? ? ? ? 83 F8 FF 74 ? 8B 89 ? ? ? ? EB ? ? ? ? 8B 00 83 F8 FF 74 ? 8D 04 ? 8D 04 ? 3B 50"
follow_mode = "None"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::IClientUtils::RunIPCFrame"
name = "IClientUtils::RunIPCFrame"
target_rva = 21468320
match_rva = 21469236
signature = "83 EC 08 89 F3 50 57 E8 ? ? ? ? 58 FF B5 ? ? ? ? E8 ? ? ? ? 58 8D 45"
follow_mode = "PrologueUpwards"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::ParentalSettingsReceived"
name = "ParentalSettingsReceived"
target_rva = 25873952
match_rva = 25873952
signature = "55 89 E5 57 56 E8 ? ? ? ? 81 C6 ? ? ? ? 53 81 EC 00 02 00 00 8B 45 08 8B 55 1C 8B 7D 0C"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::ParentalSignatureCheck"
name = "ParentalSignatureCheck"
target_rva = 25872444
match_rva = 25872444
signature = "84 C0 75 27 8B 85 ? ? ? ? 8D 9D ? ? ? ? 83 EC 04 FF B0 82 01 00 00 8D 86 ? ? ? ? 50 53 E8 ? ? ? ?"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::StopPlayingBorrowedApp"
name = "StopPlayingBorrowedApp"
target_rva = 17401264
match_rva = 17401460
signature = "8B 40 ? 83 EC 0C 89 F3 8B 95"
follow_mode = "PrologueUpwards"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::TraceIPC"
name = "TraceIPC"
target_rva = 27435936
match_rva = 21323730
signature = "E8 ? ? ? ? 83 C4 10 85 FF 74 ? 8B 07 83 EC 04 FF B5 ? ? ? ? FF B5 ? ? ? ? 57 FF 10 83 C4 10 8D 45 ? 83 EC 04 89 F3 6A 04 50 FF 75"
follow_mode = "Relative"
resolver = "signature"
required = true
match_count = 1
target_count = 1
