schema = 1
platform = "linux32"
component = "steamui"
module_name = "steamui.so"
module_sha256 = "3ec98634c4ff98cb60e486a900b299a1972ee9193aad35ef3a5bf9e8f545a1d3"
module_size = 39277132
gnu_build_id = "5018d31c5a5bf7a57b566958e14377403f54f6ee"
steam_version = 1788209227
consumer_commit = "d3402a1800e647778db7fb8a2bb900ea24991dc3"
minimum_consumer_schema = 1
revision = 1
source = "deterministic"

[[locators]]
symbol = "Patterns::ISteamMatchmakingPingResponse::ServerResponded"
name = "ISteamMatchmakingPingResponse::ServerResponded"
target_rva = 24383616
match_rva = 24383673
signature = "8B 85 ? ? ? ? 8B 40 ? 85 C0 0F 84 ? ? ? ? 39 46"
follow_mode = "PrologueUpwards"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::SteamUI::AppControllerRunFrame"
name = "CSteamUIAppController::RunFrame"
target_rva = 25167264
match_rva = 25167264
signature = "55 57 56 53 E8 ? ? ? ? 81 C3 ? ? ? ? 83 EC 7C E8 ? ? ? ? 8B 84 24 90 00 00 00 D9 5C 24 0C D9 44 24 0C"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::SteamUI::BuildCompleteAppOverviewChange"
name = "BuildCompleteAppOverviewChange"
target_rva = 25106144
match_rva = 25106144
signature = "55 89 E5 57 56 53 E8 ? ? ? ? 81 C3 ? ? ? ? 81 EC 8C 00 00 00 8B 7D 08 89 5D A4 E8 ? ? ? ? 84 C0"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::SteamUI::GetAppByID"
name = "CSteamUIAppController::GetAppByID"
target_rva = 25221408
match_rva = 25221408
signature = "E8 ? ? ? ? 05 ? ? ? ? 55 89 E5 57 56 53 83 EC 4C 8B 5D 10 8B 75 08 89 45 C8 8B 80 E0 09 00 00"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::SteamUI::MarkAppChange"
name = "CUpdateManager::MarkAppChange"
target_rva = 26557776
match_rva = 26557776
signature = "E8 ? ? ? ? 05 ? ? ? ? 55 89 E5 57 56 53 83 EC 3C 8B 75 0C 8B 5D 10 89 45 D4 8B 80 E0 09 00 00"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::SteamUI::OwnershipFlagsReference"
name = "CSteamApp::OwnershipFlagsReference"
target_rva = 25124228
match_rva = 25124228
signature = "8B ? 18 8B 9D ? ? ? ? 83 EC 04 50 8D 83 ? ? ? ? 50 FF B5 ? ? ? ? E8 ? ? ? ?"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1
