schema = 1
platform = "linux32"
component = "steamui"
module_name = "steamui.so"
module_sha256 = "8c77009990cb21cee14628dcb8b2aa417c598f5194b18a25e0cb516e4e36db39"
module_size = 39277132
gnu_build_id = "a856fa76c939b5b0e9441a343dcb348a0d5390ec"
steam_version = 1788652215
consumer_commit = "edfc7ea975f5b64d1c3ae86ac41bd9bf059d1cb8"
minimum_consumer_schema = 1
revision = 3
source = "deterministic"

[[locators]]
symbol = "Patterns::ISteamMatchmakingPingResponse::ServerResponded"
name = "ISteamMatchmakingPingResponse::ServerResponded"
target_rva = 24383664
match_rva = 24383721
signature = "8B 85 ? ? ? ? 8B 40 ? 85 C0 0F 84 ? ? ? ? 39 46"
follow_mode = "PrologueUpwards"
resolver = "signature"
required = true
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::SteamUI::AppControllerRunFrame"
name = "CSteamUIAppController::RunFrame"
target_rva = 25167312
match_rva = 25167312
signature = "55 57 56 53 E8 ? ? ? ? 81 C3 ? ? ? ? 83 EC 7C E8 ? ? ? ? 8B 84 24 90 00 00 00 D9 5C 24 0C D9 44 24 0C"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::SteamUI::BuildCompleteAppOverviewChange"
name = "BuildCompleteAppOverviewChange"
target_rva = 25106192
match_rva = 25106192
signature = "55 89 E5 57 56 53 E8 ? ? ? ? 81 C3 ? ? ? ? 81 EC 8C 00 00 00 8B 7D 08 89 5D A4 E8 ? ? ? ? 84 C0"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::SteamUI::GetAppByID"
name = "CSteamUIAppController::GetAppByID"
target_rva = 25221456
match_rva = 25221456
signature = "E8 ? ? ? ? 05 ? ? ? ? 55 89 E5 57 56 53 83 EC 4C 8B 5D 10 8B 75 08 89 45 C8 8B 80 ? ? 00 00"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::SteamUI::MarkAppChange"
name = "CUpdateManager::MarkAppChange"
target_rva = 26557824
match_rva = 26557824
signature = "E8 ? ? ? ? 05 ? ? ? ? 55 89 E5 57 56 53 83 EC 3C 8B 75 0C 8B 5D 10 89 45 D4 8B 80 ? ? 00 00"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1

[[locators]]
symbol = "Patterns::SteamUI::OwnershipFlagsReference"
name = "CSteamApp::OwnershipFlagsReference"
target_rva = 25124276
match_rva = 25124276
signature = "8B ? 18 8B 9D ? ? ? ? 83 EC 04 50 8D 83 ? ? ? ? 50 FF B5 ? ? ? ? E8 ? ? ? ?"
follow_mode = "None"
resolver = "signature"
required = false
match_count = 1
target_count = 1
