schema = 1
platform = "linux32"
component = "steamui"
module_name = "steamui.so"
module_sha256 = "9d9b126c02d7d7b6f2ef7bc6c8d1d9fb5254653b0bc2480e11394f1cbc88f294"
module_size = 39234348
gnu_build_id = "d293cd907827cf2dc982cf5890a4447137ac7f22"
steam_version = 1786491548
consumer_commit = "1668847593433088472814782be29c55734345e5"
minimum_consumer_schema = 1
revision = 1
source = "deterministic"

[[locators]]
symbol = "Patterns::ISteamMatchmakingPingResponse::ServerResponded"
name = "ISteamMatchmakingPingResponse::ServerResponded"
target_rva = 24351776
match_rva = 24351833
signature = "8B 85 ? ? ? ? 8B 40 ? 85 C0 0F 84 ? ? ? ? 39 46"
follow_mode = "PrologueUpwards"
resolver = "signature"
required = true
match_count = 1
target_count = 1
